#!/usr/bin/env python3

from os import makedirs
import numpy as np
import matplotlib.pyplot as plt

from sys import argv
if len(argv) <= 1:
    print(f'usage: {argv[0]} FILE1 FILE2 ... FILEN')
    exit()
files = argv[1:]

stack = np.mean([np.load(p) for p in files], axis=0)

plt.imshow(stack, origin="lower")
plt.colorbar()

makedirs("plots", exist_ok=True)
plt.savefig("plots/mean.png", dpi=150, bbox_inches="tight")
