#!/usr/bin/env python3

from os import path, makedirs
from glob import glob
import numpy as np
from ccdmini.calib import make_master_bias, make_master_dark, make_master_flat

mkref = {
    'bias': make_master_bias,
    'dark': make_master_dark,
    'flat': make_master_flat,    
}

def load_dir(d):
    return [np.load(p) for p in sorted(glob(path.join(d, "*.npy")))]

from sys import argv
if len(argv) < 3:
    print(f'usage: {argv[0]} [bias|dark|flat] DIR')
    exit()

kind = argv[1]
data = argv[2]

makedirs("results/ref", exist_ok=True)
np.save(f"results/ref/{kind}.npy", mkref[kind](load_dir(data)))
