name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install
        run: |
          pip install -U pip
          pip install flake8
          pip install -e .
      - name: Lint
        run: flake8 src tests --max-line-length=100
